### ISSUE TITLE
System.InvalidOperationException: 'Sequence contains no matching element'

### ISSUE THREAD

**Issue by Symbai** [BadRyuner/MonoTrainer#1]
I've tried running the generator on Endless Space 2 and I got an exception on line:

https://github.com/BadRyuner/MonoTrainer/blob/06be44ad705f80efd45a8930d3f41f26689f9005/SDKGenerator/Generator.cs#L758

`System.InvalidOperationException: 'Sequence contains no matching element'`

The only thing that exists and comes close to `m_firstChar_offset` is `{System.UInt32 GameSDK.mscorlib.System.String::start_char_offset}` and for `get_m_stringLength` it might be `get_length`. If I use these two instead it completes without any issue.

If you need the `Assembly-CSharp.dll` file let me know how I can give it to you.

**Comment by BadRyuner** [comment]
Fixed this problem in the new version.
I tried this game, it uses a lot of generic methods and methods with an out parameter, which greatly limits the capabilities of this library.
