### ISSUE TITLE
How to access Unity classes?

### ISSUE THREAD

**Issue by Symbai** [BadRyuner/MonoTrainer#4]
Ive used the SDK on Cities Skyline 2. I'm trying to cheat money. In order to get the instance of the PlayerMoney class Im trying to follow what the game does:

`PlayerMoney componentData = Unity.Entities.EntityManager.GetComponentData<PlayerMoney>(m_City);`

However unity classes are not defined in the SDK. I've generated the SDK without using a whitelist. Also tried with `--get-everything-from-mscorlib` but no success. Any idea?

**Comment by BadRyuner** [comment]
I tried fixing it... But it seems to be an unfixable problem considering how mono native functions work. Also I can't implement Generic methods because Type.GetMethod(string, flags) refuses to return the correct method. And probably MakeGenericMethod will also return null....

**Comment by Symbai** [comment]
Ah ok, thanks for trying though
